::
:: This script prepares the project for uploading to Github.
:: It deletes all visual studio generated files that can be
:: regenerated by another user.
::
:: Close Visual Studio before running or some files may not be
:: deleted because they are still open in the IDE.
::
@echo off
FOR /F "delims=" %%I IN ('DIR /AD /D /B /S 2^>NUL ^| FINDSTR /I /E /C:"\ipch" /C:"\Debug" /C:"\Release" /C:"\x64" ^| FINDSTR /V /I /C:"\x64\Debug" /C:"\x64\Release"') DO @RD /S /Q "%%I"
FOR /F "delims=" %%I IN ('DIR /D /B /S 2^>NUL ^| FINDSTR /I /E /C:".suo" /C:".sdf" /C:".vcxproj.user"') DO @DEL "%%I"