//
// General DLL Redirects. These apply to applications, application DLLs, and DLLs
// outside of KexDir and WinDir. The DLL redirect routine strips the .dll suffix,
// if present, from the DLL name.
//

#define DLL_REDIRECT(Key, Value) {RTL_CONSTANT_STRING(_L(Key)), RTL_CONSTANT_STRING(_L(Value))},

STATIC CONST UNICODE_STRING DllRedirects[][2] = {
	DLL_REDIRECT("ntdll",										"kxnt"				)

	DLL_REDIRECT("cfgmgr32",									"kxbase"			)
	DLL_REDIRECT("kernel32",									"kxbase"			)
	DLL_REDIRECT("kernelbase",									"kxbase"			)

	DLL_REDIRECT("bcrypt",										"kxcryp"			)
	DLL_REDIRECT("ncrypt",										"kxcryp"			)
	DLL_REDIRECT("bcryptprimitives",							"kxcryp"			)
	DLL_REDIRECT("secur32",										"kxcryp"			)
	DLL_REDIRECT("security",									"kxcryp"			)
	DLL_REDIRECT("sspicli",										"kxcryp"			)

	// wininet.dll loads schannel directly but what it's really looking for is
	// secur32 functions. Loading kxschanl is not appropriate and will result
	// in error messages.
	DLL_REDIRECT("schannel",									"kxcryp"			)
	
	DLL_REDIRECT("BluetoothApis",								"kxuser"			)
	DLL_REDIRECT("shcore",										"kxuser"			)
	DLL_REDIRECT("user32",										"kxuser"			)
	DLL_REDIRECT("gamemode",									"kxuser"			)
	DLL_REDIRECT("gamingtcui",									"kxuser"			)
	
	DLL_REDIRECT("combase",										"kxcom"				)
	DLL_REDIRECT("ole32",										"kxcom"				)

	DLL_REDIRECT("msvcrt",										"kxcrt"				)
	
	DLL_REDIRECT("d3d11",										"kxdx"				)
	DLL_REDIRECT("d3d12",										"kxdx"				)
	DLL_REDIRECT("d2d1",										"kxdx"				)
	DLL_REDIRECT("dcomp",										"kxdx"				)
	DLL_REDIRECT("dxgi",										"kxdx"				)
	DLL_REDIRECT("MFPlat",										"kxdx"				)
	DLL_REDIRECT("mshtmlmedia",									"kxdx"				)
	DLL_REDIRECT("opengl32",									"kxdx"				)
	DLL_REDIRECT("xinput1_4",									"xinput1_3"			)

	// Note: CreateAudioReverb between XAudio 2.8 and 2.9 has a different structure
	// layout for the reverb parameters. If encountering games which have weird-sounding
	// audio or which have broken reverb effects, a proper shim needs to be constructed.
	DLL_REDIRECT("XAudio2_8",									"XAudio2_9"			)

	DLL_REDIRECT("powrprof",									"kx"				)
	DLL_REDIRECT("userenv",										"kx"				)
	DLL_REDIRECT("version",										"kx"				)
	DLL_REDIRECT("wldp",										"kx"				)
	DLL_REDIRECT("wtsapi32",									"kx"				)
	DLL_REDIRECT("uiautomationcore",							"kx"				)
	DLL_REDIRECT("coremessaging",								"kx"				)
	DLL_REDIRECT("imm32",										"kx"				)
	DLL_REDIRECT("tbs",											"kx"				)

	DLL_REDIRECT("dnsapi",										"kxnet"				)
	DLL_REDIRECT("winhttp",										"kxnet"				)
	DLL_REDIRECT("ws2_32",										"kxnet"				)

	DLL_REDIRECT("advapi32",									"kxadvapi"			)
	DLL_REDIRECT("sechost",										"kxadvapi"			)

	// On Windows 10/11, icuin.dll and icuuc.dll just contain export forwarders to
	// icu.dll. icu.dll contains all the functionality of icuin and icuuc in one DLL.
	DLL_REDIRECT("icuin",										"icu"				)
	DLL_REDIRECT("icuuc",										"icu"				)

	//
	// The DLL rewriting routine strips the -lX-Y-Z suffix from the API set name to
	// avoid excessive duplication.
	// Keep this list in alphabetical order to avoid accidental duplicates.
	//

	DLL_REDIRECT("api-ms-win-appmodel-identity",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-appmodel-runtime",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-appmodel-runtime-internal",		"kxbase"			)
	DLL_REDIRECT("api-ms-win-appmodel-state",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-appmodel-unlock",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-base-bootconfig",					"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-base-util",						"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-composition-redirection",			"dwmredir"			)
	DLL_REDIRECT("api-ms-win-composition-windowmanager",		"udwm"				)
	DLL_REDIRECT("api-ms-win-core-apiquery",					"kxnt"				)
	DLL_REDIRECT("api-ms-win-core-appcompat",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-appinit",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-atoms",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-backgroundtask",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-calendar",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-com",							"kxcom"				)
	DLL_REDIRECT("api-ms-win-core-com-midlproxystub",			"kxcom"				)
	DLL_REDIRECT("api-ms-win-core-com-private",					"kxcom"				)
	DLL_REDIRECT("api-ms-win-core-comm",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-console",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-console-ansi",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-crt",							"kxcrt"				)
	DLL_REDIRECT("api-ms-win-core-datetime",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-debug",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-debug-minidump",				"dbgcore"			)
	DLL_REDIRECT("api-ms-win-core-delayload",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-enclave",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-errorhandling",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-featurestaging",				"kxuser"			)
	DLL_REDIRECT("api-ms-win-core-fibers",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-file",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-file-ansi",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-file-fromapp",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-firmware",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-guard",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-handle",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-heap",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-heap-obsolete",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-interlocked",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-io",							"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-job",							"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-kernel32-legacy-ansi",		"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-kernel32-legacy",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-kernel32-private",			"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-largeinteger",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-libraryloader",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-libraryloader-private",		"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-localization",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-localization-ansi",			"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-localization-obsolete",		"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-localization-private",		"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-localregistry",				"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-core-marshal",						"kxcom"				)
	DLL_REDIRECT("api-ms-win-core-memory",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-misc",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-multipleproviderrouter",		"mpr"				)
	DLL_REDIRECT("api-ms-win-core-namedpipe",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-namedpipe-ansi",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-namespace",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-namespace-ansi",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-normalization",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-path",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-pcw",							"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-perfcounters",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-perfstm",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-privateprofile",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-processenvironment",			"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-processenvironment-ansi",		"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-processsecurity",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-processsnapshot",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-processthreads",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-processtopology",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-processtopology-obsolete",	"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-processtopology-private",		"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-profile",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-psapi",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-psapiansi",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-psapi-ansi",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-psapi-obsolete",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-psm-app",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-psm-appnotify",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-psm-info",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-psm-key",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-psm-plm",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-psm-rtimer",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-psm-tc",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-quirks",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-realtime",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-registry",					"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-core-registry-fromapp",			"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-core-registry-private",			"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-core-registryuserspecific",		"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-core-rtlsupport",					"kxnt"				)
	DLL_REDIRECT("api-ms-win-core-shlwapi-legacy",				"kxuser"			)
	DLL_REDIRECT("api-ms-win-core-shlwapi-obsolete",			"kxuser"			)
	DLL_REDIRECT("api-ms-win-core-shutdown",					"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-core-shutdown-ansi",				"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-core-sidebyside",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-sidebyside-ansi",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-state-helpers",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-string-obsolete",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-sidebyside",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-string",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-stringansi",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-stringloader",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-string-obsolete",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-synch",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-synch-ansi",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-sysinfo",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-systemtopology",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-threadpool",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-threadpool-legacy",			"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-threadpool-private",			"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-timezone",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-timezone-private",			"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-toolhelp",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-ums",							"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-url",							"kxuser"			)
	DLL_REDIRECT("api-ms-win-core-util",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-version",						"version"			)
	DLL_REDIRECT("api-ms-win-core-versionansi",					"version"			)
	DLL_REDIRECT("api-ms-win-core-version-private",				"version"			)
	DLL_REDIRECT("api-ms-win-core-windowsceip",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-windowserrorreporting",		"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-winrt",						"kxcom"				)
	DLL_REDIRECT("api-ms-win-core-winrt-error",					"kxcom"				)
	DLL_REDIRECT("api-ms-win-core-winrt-errorprivate",			"kxcom"				)
	DLL_REDIRECT("api-ms-win-core-winrt-propertysetprivate",	"kxcom"				)
	DLL_REDIRECT("api-ms-win-core-winrt-registration",			"kxcom"				)
	DLL_REDIRECT("api-ms-win-core-winrt-robuffer",				"kxcom"				)
	DLL_REDIRECT("api-ms-win-core-winrt-roparameterizediid",	"kxcom"				)
	DLL_REDIRECT("api-ms-win-core-winrt-string",				"kxcom"				)
	DLL_REDIRECT("api-ms-win-core-wow64",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-core-xstate",						"kxbase"				)
	DLL_REDIRECT("api-ms-win-crt-conio",						"ucrtbase"			)
	DLL_REDIRECT("api-ms-win-crt-convert",						"ucrtbase"			)
	DLL_REDIRECT("api-ms-win-crt-environment",					"ucrtbase"			)
	DLL_REDIRECT("api-ms-win-crt-filesystem",					"ucrtbase"			)
	DLL_REDIRECT("api-ms-win-crt-heap",							"ucrtbase"			)
	DLL_REDIRECT("api-ms-win-crt-locale",						"ucrtbase"			)
	DLL_REDIRECT("api-ms-win-crt-math",							"ucrtbase"			)
	DLL_REDIRECT("api-ms-win-crt-multibyte",					"ucrtbase"			)
	DLL_REDIRECT("api-ms-win-crt-private",						"ucrtbase"			)
	DLL_REDIRECT("api-ms-win-crt-process",						"ucrtbase"			)
	DLL_REDIRECT("api-ms-win-crt-runtime",						"ucrtbase"			)
	DLL_REDIRECT("api-ms-win-crt-stdio",						"ucrtbase"			)
	DLL_REDIRECT("api-ms-win-crt-string",						"ucrtbase"			)
	DLL_REDIRECT("api-ms-win-crt-time",							"ucrtbase"			)
	DLL_REDIRECT("api-ms-win-crt-utility",						"ucrtbase"			)
	DLL_REDIRECT("api-ms-win-devices-config",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-devices-query",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-devices-swdevice",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-downlevel-advapi32",				"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-downlevel-kernel32",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-downlevel-normaliz",				"normaliz"			)
	DLL_REDIRECT("api-ms-win-downlevel-ole32",					"kxcom"				)
	DLL_REDIRECT("api-ms-win-downlevel-shell32",				"shell32"			)
	DLL_REDIRECT("api-ms-win-downlevel-shlwapi",				"shlwapi"			)
	DLL_REDIRECT("api-ms-win-downlevel-user32",					"kxuser"			)
	DLL_REDIRECT("api-ms-win-downlevel-version",				"version"			)
	DLL_REDIRECT("api-ms-win-dwmapi",							"dwmapi"			)
	DLL_REDIRECT("api-ms-win-dx-d3dkmt",						"gdi32"				)
	DLL_REDIRECT("api-ms-win-eventing-classicprovider",			"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-eventing-consumer",				"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-eventing-controller",				"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-eventing-legacy",					"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-eventing-provider",				"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-eventing-tdh",						"tdh"				)
	DLL_REDIRECT("api-ms-win-eventlog-legacy",					"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-eventlog-private",					"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-gaming-deviceinformation",			"kxbase"			)
	DLL_REDIRECT("api-ms-win-gaming-expandedresources",			"kxuser"			)
	DLL_REDIRECT("api-ms-win-gaming-tcui",						"kxuser"			)
	DLL_REDIRECT("api-ms-win-gdi-dpiinfo",						"gdi32"				)
	DLL_REDIRECT("api-ms-win-gdi-internal-uap",					"gdi32"				)
	DLL_REDIRECT("api-ms-win-http-time",						"kxbase"			)
	DLL_REDIRECT("api-ms-win-kernel32-package-current",			"kxbase"			)
	DLL_REDIRECT("api-ms-win-legacy-shlwapi",					"shlwapi"			)
	DLL_REDIRECT("api-ms-win-mm-joystick",						"winmm"				)
	DLL_REDIRECT("api-ms-win-mm-mci",							"winmm"				)
	DLL_REDIRECT("api-ms-win-mm-misc",							"winmm"				)
	DLL_REDIRECT("api-ms-win-mm-mme",							"winmm"				)
	DLL_REDIRECT("api-ms-win-mm-playsound",						"winmm"				)
	DLL_REDIRECT("api-ms-win-mm-time",							"winmm"				)
	DLL_REDIRECT("api-ms-win-net-isolation",					"firewallapi"		)
	DLL_REDIRECT("api-ms-win-ntuser-ie-message",				"kxuser"			)
	DLL_REDIRECT("api-ms-win-ntuser-ie-window",					"kxuser"			)
	DLL_REDIRECT("api-ms-win-ntuser-ie-wmpointer",				"kxuser"			)
	DLL_REDIRECT("api-ms-win-ntuser-rectangle",					"kxuser"			)
	DLL_REDIRECT("api-ms-win-ntuser-sysparams",					"kxuser"			)
	DLL_REDIRECT("api-ms-win-obsolete-localization",			"kxbase"			)
	DLL_REDIRECT("api-ms-win-obsolete-psapi",					"psapi"				)
	DLL_REDIRECT("api-ms-win-obsolete-shlwapi",					"shlwapi"			)
	DLL_REDIRECT("api-ms-win-ole32-ie",							"kxcom"				)
	DLL_REDIRECT("api-ms-win-oobe-notification",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-perf-legacy",						"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-power-base",						"kx"				)
	DLL_REDIRECT("api-ms-win-power-limitsmanagement",			"kx"				)
	DLL_REDIRECT("api-ms-win-power-setting",					"kx"				)
	DLL_REDIRECT("api-ms-win-ro-typeresolution",				"kxcom"				)
	DLL_REDIRECT("api-ms-win-rtcore-ntuser-clipboard",			"kxuser"			)
	DLL_REDIRECT("api-ms-win-rtcore-ntuser-draw",				"kxuser"			)
	DLL_REDIRECT("api-ms-win-rtcore-ntuser-powermanagement",	"kxuser"			)
	DLL_REDIRECT("api-ms-win-rtcore-ntuser-private",			"kxuser"			)
	DLL_REDIRECT("api-ms-win-rtcore-ntuser-shell",				"kxuser"			)
	DLL_REDIRECT("api-ms-win-rtcore-ntuser-synch",				"kxuser"			)
	DLL_REDIRECT("api-ms-win-rtcore-ntuser-window",				"kxuser"			)
	DLL_REDIRECT("api-ms-win-rtcore-ntuser-winevent",			"kxuser"			)
	DLL_REDIRECT("api-ms-win-rtcore-ntuser-wmpointer",			"kxuser"			)
	DLL_REDIRECT("api-ms-win-rtcore-ole32-clipboard",			"kxcom"				)
	DLL_REDIRECT("api-ms-win-security-accesshlpr",				"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-activedirectoryclient",	"kxbase"			)
	DLL_REDIRECT("api-ms-win-security-appcontainer",			"kxbase"			)
	DLL_REDIRECT("api-ms-win-security-audit",					"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-base",					"kxbase"			)
	DLL_REDIRECT("api-ms-win-security-base-ansi",				"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-base-private",			"kxbase"			)
	DLL_REDIRECT("api-ms-win-security-capability",				"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-cpwl",					"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-credentials",				"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-cryptoapi",				"cryptsp"			)
	DLL_REDIRECT("api-ms-win-security-grouppolicy",				"kxbase"			)
	DLL_REDIRECT("api-ms-win-security-isolatedcontainer",		"kxuser"			)
	DLL_REDIRECT("api-ms-win-security-isolationapi",			"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-isolationpolicy",			"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-logon",					"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-lsalookup",				"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-lsalookup-ansi",			"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-provider",				"ntmarta"			)
	DLL_REDIRECT("api-ms-win-security-provider-ansi",			"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-sddl",					"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-sddlparsecond",			"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-sddl-ansi",				"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-sddl-private",			"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-systemfunctions",			"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-security-trustee",					"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-service-core",						"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-service-core-ansi",				"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-service-management",				"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-service-private",					"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-service-winsvc",					"kxadvapi"			)
	DLL_REDIRECT("api-ms-win-shcore-comhelpers",				"kxuser"			)
	DLL_REDIRECT("api-ms-win-shcore-obsolete",					"kxuser"			)
	DLL_REDIRECT("api-ms-win-shcore-path",						"kxuser"			)
	DLL_REDIRECT("api-ms-win-shcore-registry",					"kxuser"			)
	DLL_REDIRECT("api-ms-win-shcore-scaling",					"kxuser"			)
	DLL_REDIRECT("api-ms-win-shcore-stream",					"kxuser"			)
	DLL_REDIRECT("api-ms-win-shcore-stream-winrt",				"kxuser"			)
	DLL_REDIRECT("api-ms-win-shcore-sysinfo",					"kxuser"			)
	DLL_REDIRECT("api-ms-win-shcore-taskpool",					"kxuser"			)
	DLL_REDIRECT("api-ms-win-shcore-thread",					"kxuser"			)
	DLL_REDIRECT("api-ms-win-shcore-unicodeansi",				"kxuser"			)
	DLL_REDIRECT("api-ms-win-shell-associations",				"kxuser"			)
	DLL_REDIRECT("api-ms-win-shell-changenotify",				"kxuser"			)
	DLL_REDIRECT("api-ms-win-shell-dataobject",					"kxuser"			)
	DLL_REDIRECT("api-ms-win-shell-namespace",					"kxuser"			)
	DLL_REDIRECT("api-ms-win-shell-shdirectory",				"kxuser"			)
	DLL_REDIRECT("api-ms-win-shell-shellcom",					"kxuser"			)
	DLL_REDIRECT("api-ms-win-shell-shellfolders",				"kxuser"			)
	DLL_REDIRECT("api-ms-win-shlwapi-ie",						"shlwapi"			)
	DLL_REDIRECT("api-ms-win-shlwapi-winrt-storage",			"shlwapi"			)
	DLL_REDIRECT("api-ms-win-stateseparation-helpers",			"kxbase"			)
	DLL_REDIRECT("api-ms-win-winrt-search-folder",				"kxcom"				)
	DLL_REDIRECT("api-ms-win-wsl-api",							"kxbase"			)

	DLL_REDIRECT("ext-ms-win-gdi-dc",							"gdi32"				)
	DLL_REDIRECT("ext-ms-win-gdi-dc-create",					"gdi32"				)
	DLL_REDIRECT("ext-ms-win-gdi-draw",							"gdi32"				)
	DLL_REDIRECT("ext-ms-win-gdi-font",							"gdi32"				)
	DLL_REDIRECT("ext-ms-win-gdi-path",							"gdi32"				)
	DLL_REDIRECT("ext-ms-win-ntuser-gui",						"kxuser"			)
	DLL_REDIRECT("ext-ms-win-ntuser-rectangle-ext",				"kxuser"			)
	DLL_REDIRECT("ext-ms-win-ntuser-rotationmanager",			"kxuser"			)
	DLL_REDIRECT("ext-ms-win-ntuser-window",					"kxuser"			)
	DLL_REDIRECT("ext-ms-win-rtcore-gdi-devcaps",				"gdi32"				)
	DLL_REDIRECT("ext-ms-win-rtcore-gdi-object",				"gdi32"				)
	DLL_REDIRECT("ext-ms-win-rtcore-gdi-rgn",					"gdi32"				)
	DLL_REDIRECT("ext-ms-win-rtcore-ntuser-dc-access",			"kxuser"			)
	DLL_REDIRECT("ext-ms-win-rtcore-ntuser-sysparams",			"kxuser"			)
	DLL_REDIRECT("ext-ms-win-uiacore",							"kx"				)
	DLL_REDIRECT("ext-ms-win-wevtapi-eventlog",					"wevtapi"			)
};

#undef DLL_REDIRECT