#pragma once

#define IDSTATIC				-1


#define IDD_DIALOG1					100

#define IDC_ENABLELOGGING			101
#define IDC_LOGDIR					102
#define IDC_BROWSELOGDIR			103

#define IDC_ENABLEFORMSI			110
#define IDC_CPIWBYPA				111
#define IDC_ADDTOMENU				112
#define IDC_WHICHCONTEXTMENU		113

#define IDC_LISTVIEW				120
#define IDC_NEWAPP					121
#define IDC_REMOVEAPPS				122
#define IDC_PROPERTIES				123


#define IDM_LISTVIEWITEMMENU		200
#define M_OPENFILELOCATION			201
#define M_RUNPROGRAM				202
#define M_REMOVE					203
#define M_PROPERTIES				204

#define IDM_LISTVIEWBLANKSPACEMENU	210
#define M_ADDPROGRAM				211

#define IDM_LISTVIEWMULTIITEMMENU	220


#define IDC_APPLY					190
#define IDC_OK						191
#define IDC_CANCEL					192


#define IDI_APPICON					501




