#include <Windows.h>
#include <WindowsX.h>
#include <WinNT.h>
#include <Shlwapi.h>
#include <KexComm.h>
#include <NtDll.h>

#include "resource.h"

#define APPNAME L"KexExprt"

#ifdef _M_X64
#  define FRIENDLYAPPNAME L"Module-Definition File Generator (64 bit)"
#else
#  define FRIENDLYAPPNAME L"Module-Definition File Generator (32 bit)"
#endif

#ifdef _M_X64
#  define BITS 64
#else
#  define BITS 32
#endif

DWORD WINAPI ThreadProc(
	IN	LPVOID	lpParameter)
{
#define RVA_TO_VA(rva) (((LPBYTE) hMod) + (rva))

	HWND hWnd = (HWND) lpParameter;
	HWND hWndEdit = GetDlgItem(hWnd, IDRESULT);
	WCHAR szDllPath[MAX_PATH];
	HMODULE hMod;
	HANDLE hProc = GetCurrentProcess();
	UINT i;

	HANDLE hTempFile = CreateTempFile(L"kxp", GENERIC_READ | GENERIC_WRITE, FILE_SHARE_READ, NULL);
	HANDLE hMapping;
	LPCWSTR lpszDocument;
	DWORD dwDiscard;

	PIMAGE_DOS_HEADER lpDosHdr;
	PIMAGE_NT_HEADERS lpNtHdr;
	PIMAGE_EXPORT_DIRECTORY lpExportDir;

	LPDWORD lpNameRvas;
	LPWORD lpNameOrdinals;
	LPDWORD lpFunctionRvas;
	PBOOLEAN lpOrdinalHasName;

	BOOL bPragma = FALSE;

	GetDlgItemText(hWnd, IDFILEPATH, szDllPath, ARRAYSIZE(szDllPath));
	hMod = LoadLibraryEx(szDllPath, NULL, DONT_RESOLVE_DLL_REFERENCES);

	if (!hMod) {
		ErrorBoxF(L"Could not load the DLL file \"%s\": %s"), szDllPath, GetLastErrorAsString();
		goto FinishThreadProc;
	}

	if (IsDlgButtonChecked(hWnd, IDRBPRAGMA)) {
		bPragma = TRUE;
	}

	GetModuleFileName(hMod, szDllPath, ARRAYSIZE(szDllPath));
	WriteFileWF(hTempFile, L"%s Generated by KexExprt (%d bit) from %s\r\n", bPragma ? L"//" : L";;", BITS, szDllPath);
	PathStripPath(szDllPath);
	PathRemoveExtension(szDllPath);

	lpDosHdr = (PIMAGE_DOS_HEADER) hMod;
	lpNtHdr = (PIMAGE_NT_HEADERS) RVA_TO_VA(lpDosHdr->e_lfanew);

	if (lpNtHdr->OptionalHeader.NumberOfRvaAndSizes == 0) {
		InfoBoxF(L"This DLL contains no exports.");
		goto FinishThreadProc;
	}

	lpExportDir = (PIMAGE_EXPORT_DIRECTORY) RVA_TO_VA(lpNtHdr->OptionalHeader.DataDirectory[0].VirtualAddress);
	lpNameRvas = (LPDWORD) RVA_TO_VA(lpExportDir->AddressOfNames);
	lpNameOrdinals = (LPWORD) RVA_TO_VA(lpExportDir->AddressOfNameOrdinals);
	lpFunctionRvas = (LPDWORD) RVA_TO_VA(lpExportDir->AddressOfFunctions);
	lpOrdinalHasName = (PBOOLEAN) AutoAlloc(lpExportDir->NumberOfFunctions);
	ZeroMemory(lpOrdinalHasName, lpExportDir->NumberOfFunctions);

	if (!bPragma) {
		WriteFileWF(hTempFile, L"EXPORTS\r\n");
	}

	for (i = 0; i < lpExportDir->NumberOfNames; ++i) {
		LPCSTR lpszName = (LPCSTR) RVA_TO_VA(lpNameRvas[i]);
		WORD wNameOrdinal = lpNameOrdinals[i];
		DWORD dwOrdinal = lpExportDir->Base + wNameOrdinal;
		
		if (bPragma) {
			WriteFileWF(hTempFile, L"#pragma comment(linker, \"/export:%hs=%s.%hs,@%I32u\")\r\n", lpszName, szDllPath, lpszName, dwOrdinal);
		} else {
			WriteFileWF(hTempFile, L"\t%hs = %s.%hs @%I32u\r\n", lpszName, szDllPath, lpszName, dwOrdinal);
		}

		lpOrdinalHasName[wNameOrdinal] = TRUE;
	}

	for (i = 0; i < lpExportDir->NumberOfFunctions; ++i) {
		DWORD dwOrdinal = lpExportDir->Base + i;
		
		if (lpOrdinalHasName[i] != TRUE && lpFunctionRvas[dwOrdinal - lpExportDir->Base] != 0) {
			if (bPragma) {
				WriteFileWF(hTempFile, L"#pragma comment(linker, \"/export:__OrdinalFunction%I32X=%s.#%I32u,@%I32u,NONAME\")\r\n", dwOrdinal, szDllPath, dwOrdinal, dwOrdinal);
			} else {
				WriteFileWF(hTempFile, L"\t__OrdinalFunction%I32X = %s.#%I32u @%I32u NONAME\r\n", dwOrdinal, szDllPath, dwOrdinal, dwOrdinal);
			}
		}
	}

	AutoFree(lpOrdinalHasName);

	WriteFile(hTempFile, L"", sizeof(WCHAR), &dwDiscard, NULL);
	hMapping = CreateFileMapping(hTempFile, NULL, PAGE_READONLY, 0, 0, NULL);
	lpszDocument = (LPCWSTR) MapViewOfFile(hMapping, FILE_MAP_READ, 0, 0, 0);
	Edit_SetText(hWndEdit, lpszDocument);
	UnmapViewOfFile(lpszDocument);
	CloseHandle(hMapping);
	CloseHandle(hTempFile);
	
FinishThreadProc:
	EnableWindow(GetDlgItem(hWnd, IDFILEPATH), TRUE);
	EnableWindow(GetDlgItem(hWnd, IDOK), TRUE);
	FreeLibrary(hMod);
	ExitThread(0);

#undef RVA_TO_VA
}

HGDIOBJ SetStaticCtlBk(
	IN	HWND	hWndDlg,
	IN	HWND	hWndCtl,
	IN	HDC		hDC)
{
	if (GetWindowLongPtr(hWndCtl, GWLP_ID) == IDRESULT) {
		// Note: don't use hollow brush, that causes glitches when you change the text
		// in a text control.
		return GetStockObject(WHITE_BRUSH);
	}

	return FALSE;
}

INT_PTR CALLBACK DlgProc(
	IN	HWND	hWnd,
	IN	UINT	uMsg,
	IN	WPARAM	wParam,
	IN	LPARAM	lParam)
{
	UINT uTabStops = 16;
	WCHAR szFilename[MAX_PATH] = L"";

	switch (uMsg) {
	case WM_INITDIALOG:
		SetWindowText(hWnd, FRIENDLYAPPNAME);
		EnableWindow(GetDlgItem(hWnd, IDOK), FALSE);
		CheckDlgButton(hWnd, IDRBDEF, TRUE);
		DragAcceptFiles(hWnd, TRUE);
		SendMessage(GetDlgItem(hWnd, IDRESULT), WM_SETFONT, (WPARAM) CreateFont(
			-MulDiv(8, GetDeviceCaps(GetDC(GetDlgItem(hWnd, IDRESULT)), LOGPIXELSY), 72),
			0, 0, 0, FW_NORMAL, 0, 0, 0, DEFAULT_CHARSET, OUT_DEFAULT_PRECIS,
			CLIP_DEFAULT_PRECIS, CLEARTYPE_QUALITY, DEFAULT_PITCH | FF_DONTCARE,
			L"Consolas"), MAKELPARAM(TRUE, 0));
		Edit_SetTabStops(GetDlgItem(hWnd, IDRESULT), 1, &uTabStops);
		return TRUE;
	case WM_COMMAND:
		if (LOWORD(wParam) == IDCANCEL) {
			EndDialog(hWnd, 0);
		} else if (LOWORD(wParam) == IDBROWSE) {
			OPENFILENAME ofn;

			if (GetFocus() == GetDlgItem(hWnd, IDFILEPATH)) {
				PostMessage(hWnd, WM_COMMAND, IDOK, 0);
				return TRUE;
			}

			ZeroMemory(&ofn, sizeof(ofn));
			ofn.lStructSize			= sizeof(ofn);
			ofn.hwndOwner			= hWnd;
			ofn.lpstrFilter			= L"Application extension (*.dll)\0*.dll\0All Files (*.*)\0*.*\0";
			ofn.lpstrFile			= szFilename;
			ofn.nMaxFile			= MAX_PATH;
			ofn.lpstrInitialDir		= L"C:\\Program Files\\";
			ofn.Flags				= OFN_FILEMUSTEXIST | OFN_HIDEREADONLY;
			ofn.lpstrDefExt			= L"exe";
			
			if (GetOpenFileName(&ofn)) {
				SetDlgItemText(hWnd, IDFILEPATH, szFilename);
			}
		} else if (LOWORD(wParam) == IDOK) {
			HANDLE hThread;
			EnableWindow(GetDlgItem(hWnd, IDOK), FALSE);
			EnableWindow(GetDlgItem(hWnd, IDFILEPATH), FALSE);

			if ((hThread = CreateThread(NULL, 0, ThreadProc, hWnd, 0, NULL))) {
				CloseHandle(hThread);
			} else {
				EnableWindow(GetDlgItem(hWnd, IDFILEPATH), TRUE);
				EnableWindow(GetDlgItem(hWnd, IDOK), TRUE);
			}
		} else if (LOWORD(wParam) == IDFILEPATH) {
			if (HIWORD(wParam) == EN_CHANGE) {
				INT iTextLength = GetWindowTextLength(GetDlgItem(hWnd, IDFILEPATH));
				EnableWindow(GetDlgItem(hWnd, IDOK), !!iTextLength);
			} else {
				return FALSE;
			}
		} else {
			return FALSE;
		}

		return TRUE;
	case WM_DROPFILES:
		DragQueryFile((HDROP) wParam, 0, szFilename, MAX_PATH);
		SetDlgItemText(hWnd, IDFILEPATH, szFilename);
		DragFinish((HDROP) wParam);
		return FALSE;
	case WM_CTLCOLORSTATIC:;
		return (INT_PTR) SetStaticCtlBk(hWnd, (HWND) lParam, (HDC) wParam);
	}

	return FALSE;
}

INT APIENTRY wWinMain(
	IN	HINSTANCE	hInstance,
	IN	HINSTANCE	hPrevInstance,
	IN	LPWSTR		lpszCmdLine,
	IN	INT			iCmdShow)
{
	SetFriendlyAppName(FRIENDLYAPPNAME);
	DialogBox(hInstance, MAKEINTRESOURCE(IDD_DIALOG1), NULL, DlgProc);
	ExitProcess(0);
}