///////////////////////////////////////////////////////////////////////////////
//
// Module Name:
//
//     KexStatus.h
//
// Abstract:
//
//     Defines custom NTSTATUS codes for VxKex.
//
// Author:
//
//     vxiiduu (17-May-2025)
//
// Environment:
//
//     Any.
//
// Revision History:
//
//     vxiiduu               17-May-2025  Initial creation.
//
///////////////////////////////////////////////////////////////////////////////

#pragma once

#define NTSTATUS_SUCCESS			(0x00000000L)
#define NTSTATUS_INFORMATIONAL		(0x40000000L)
#define NTSTATUS_WARNING			(0x80000000L)
#define NTSTATUS_ERROR				(0xC0000000L)
#define NTSTATUS_CUSTOMER			(0x20000000L)
#define DEFINE_KEX_NTSTATUS(Severity, Number) ((NTSTATUS) (NTSTATUS_CUSTOMER | Severity | Number))

// Remember to add entries to KexDll\status.c if you add more values.

#define STATUS_USER_DISABLED					DEFINE_KEX_NTSTATUS(NTSTATUS_INFORMATIONAL, 0)
#define STATUS_ALREADY_INITIALIZED				DEFINE_KEX_NTSTATUS(NTSTATUS_INFORMATIONAL, 1)
#define STATUS_ALREADY_CONNECTED				DEFINE_KEX_NTSTATUS(NTSTATUS_INFORMATIONAL, 2)

#define STATUS_IMAGE_NO_IMPORT_DIRECTORY		DEFINE_KEX_NTSTATUS(NTSTATUS_ERROR, 0)
#define STATUS_STRING_MAPPER_ENTRY_NOT_FOUND	DEFINE_KEX_NTSTATUS(NTSTATUS_ERROR, 1)
#define STATUS_REG_DATA_TYPE_MISMATCH			DEFINE_KEX_NTSTATUS(NTSTATUS_ERROR, 2)
#define STATUS_KEXDLL_INITIALIZATION_FAILURE	DEFINE_KEX_NTSTATUS(NTSTATUS_ERROR, 3)
#define STATUS_VERSION_MISMATCH					DEFINE_KEX_NTSTATUS(NTSTATUS_ERROR, 4)
#define STATUS_SOURCE_APPLICATION_MISMATCH		DEFINE_KEX_NTSTATUS(NTSTATUS_ERROR, 5)
#define STATUS_TOO_MANY_INDICES					DEFINE_KEX_NTSTATUS(NTSTATUS_ERROR, 6)
#define STATUS_INVALID_OPEN_MODE				DEFINE_KEX_NTSTATUS(NTSTATUS_ERROR, 7)
#define STATUS_KEXDATA_NOT_INITIALIZED			DEFINE_KEX_NTSTATUS(NTSTATUS_ERROR, 8)
#define STATUS_KEXSETUP_FAILURE					DEFINE_KEX_NTSTATUS(NTSTATUS_ERROR, 9)
#define STATUS_IMAGE_SECTION_NOT_FOUND			DEFINE_KEX_NTSTATUS(NTSTATUS_ERROR, 10)
#define STATUS_DLL_NOT_IN_SYSTEM_ROOT			DEFINE_KEX_NTSTATUS(NTSTATUS_ERROR, 11)
#define STATUS_PATH_TOO_SHORT					DEFINE_KEX_NTSTATUS(NTSTATUS_ERROR, 12)
#define STATUS_MLS_NOT_INITIALIZED				DEFINE_KEX_NTSTATUS(NTSTATUS_ERROR, 13)
#define STATUS_MLS_BDI_MAGIC_MISMATCH			DEFINE_KEX_NTSTATUS(NTSTATUS_ERROR, 14)
