#pragma once
#include <Windows.h>
#include <KexComm.h>
#include <KexDll.h>

typedef struct _ACVAHASHTABLEADDRESSLISTENTRY {
	LIST_ENTRY			ListEntry; // MUST BE THE FIRST MEMBER OF THIS STRUCTURE
	VOLATILE LPVOID		lpAddr;
	CONDITION_VARIABLE	CVar;
	DWORD				dwWaiters;
} ACVAHASHTABLEADDRESSLISTENTRY, *PACVAHASHTABLEADDRESSLISTENTRY, *LPACVAHASHTABLEADDRESSLISTENTRY;

typedef struct _ACVAHASHTABLEENTRY {
	LIST_ENTRY			Addresses;	// list of ACVAHASHTABLEADDRESSLISTENTRY structures
	CRITICAL_SECTION	Lock;
} ACVAHASHTABLEENTRY, *PACVAHASHTABLEENTRY, *LPACVAHASHTABLEENTRY;